# Generated by Django 3.0.3 on 2020-02-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastroast',
            old_name='boastroast',
            new_name='boolean',
        ),
        migrations.AddField(
            model_name='boastroast',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
