# Generated by Django 3.0.4 on 2020-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0003_auto_20200326_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroast',
            name='downvotes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='boastroast',
            name='upvotes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
